name: Minify, Version, and Deploy Badge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install minifiers
        run: |
          npm install -g html-minifier-terser terser

      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(grep -oP 'const VERSION = "\K[0-9]+\.[0-9]+\.[0-9]+' badge.min.js)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create directory for minified files
        run: mkdir -p minified

      - name: Minify and Rename Files
        run: |
          echo "Minifying files and appending version suffix..."

          html-minifier-terser index.html -o minified/index.html --collapse-whitespace --remove-comments
          terser badge.min.js -o minified/badge.min.${VERSION}.js --compress --mangle

      - name: Commit and Push Minified Files
        run: |
          cp minified/* .
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add minified/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Minified files for version ${VERSION} [skip ci]"
            git pull --rebase origin main
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Summary
        run: |
          echo "# 🚀 Minified Files Summary" >> $GITHUB_STEP_SUMMARY
          echo "## File Sizes After Minification" >> $GITHUB_STEP_SUMMARY
          
          for file in minified/*; do
            size=$(stat -c%s "$file")
            echo "- [$(basename "$file")](https://ratpi-studio.github.io/ratpi-badge/$(basename "$file")) : ${size} bytes" >> $GITHUB_STEP_SUMMARY
          done
