name: Minify, Version, and Deploy Badge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Increment Version
        id: increment_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          jq ".version = \"$NEW_VERSION\"" package.json > package.tmp.json && mv package.tmp.json package.json
          echo "Version updated to $NEW_VERSION"

      - name: Commit Updated Version
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add package.json
          git commit -m "Bump version to ${NEW_VERSION} [skip ci]"
          git pull --rebase origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create directory for minified files
        run: mkdir -p minified

      - name: Minify and Rename Files
        run: |
          echo "Minifying files and appending version suffix..."

          npx html-minifier-terser index.html -o minified/index.min.${NEW_VERSION}.html --collapse-whitespace --remove-comments --minify-css true --minify-js true
          npx terser badge.js -o minified/badge.min.${NEW_VERSION}.js --compress --mangle

      - name: Commit and Push Minified Files
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add minified/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Minified files for version ${NEW_VERSION} [skip ci]"
            git pull --rebase origin main
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Summary
        run: |
          echo "# 🚀 Minified Files Summary" >> $GITHUB_STEP_SUMMARY
          echo "## File Sizes After Minification" >> $GITHUB_STEP_SUMMARY
          
          for file in minified/*; do
            size=$(stat -c%s "$file")
            echo "- [$(basename "$file")](https://ratpi-studio.github.io/ratpi-badge/minified/$(basename "$file")) : ${size} bytes" >> $GITHUB_STEP_SUMMARY
          done
