name: Minify, Obfuscate, Version, and Deploy Badge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Obfuscator
        run: npm install --save-dev javascript-obfuscator

      - name: Increment Version
        id: increment_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          jq ".version = \"$NEW_VERSION\"" package.json > package.tmp.json && mv package.tmp.json package.json
          echo "Version updated to $NEW_VERSION"

      - name: Commit Updated Version
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add package.json
          git commit -m "Bump version to ${NEW_VERSION} [skip ci]"
          git pull --rebase origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create directory for minified files
        run: |
          rm -rf minified/*
          mkdir -p minified

      - name: Minify and Obfuscate HTML
        run: |
          echo "Minifying and obfuscating index.html..."
          npx html-minifier-terser index.html -o minified/index.min.${NEW_VERSION}.html \
          --collapse-boolean-attributes \
          --collapse-inline-tag-whitespace \
          --collapse-whitespace \
          --conservative-collapse \
          --decode-entities \
          --minify-css true \
          --minify-js true \
          --remove-comments \
          --remove-empty-attributes \
          --remove-optional-tags \
          --remove-redundant-attributes \
          --remove-script-type-attributes \
          --remove-style-link-type-attributes \
          --sort-attributes \
          --sort-class-name \
          --use-short-doctype

      - name: Obfuscate and Minify badge.js
        run: |
          echo "Obfuscating and minifying badge.js..."
          if [ ! -f "badge.js" ]; then
            echo "Error: badge.js not found!" >&2
            exit 1
          fi

          echo "Minifying and obfuscating index.html..."
          npx html-minifier-terser index.html -o minified/index.min.${NEW_VERSION}.html \
            --collapse-boolean-attributes \
            --collapse-inline-tag-whitespace \
            --collapse-whitespace \
            --conservative-collapse \
            --decode-entities \
            --minify-css true \
            --minify-js true \
            --remove-comments \
            --remove-empty-attributes \
            --remove-optional-tags \
            --remove-redundant-attributes \
            --remove-script-type-attributes \
            --remove-style-link-type-attributes \
            --sort-attributes \
            --sort-class-name \
            --use-short-doctype
        

          if [ -f "minified/badge.obf.${NEW_VERSION}.js" ]; then
            echo "Obfuscation successful. Copying final version..."
            cp minified/badge.obf.${NEW_VERSION}.js minified/badge.min.js
          else
            echo "Obfuscation failed!" >&2
            exit 1
          fi

      - name: Commit and Push Minified Files
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add minified/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Minified & obfuscated files for version ${NEW_VERSION} [skip ci]"
            git pull --rebase origin main
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        run: |
          git tag -a "v${NEW_VERSION}" -m "Release version ${NEW_VERSION}"
          git push origin "v${NEW_VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Summary
        run: |
          echo "# 🚀 Obfuscated Files Summary" >> $GITHUB_STEP_SUMMARY
          echo "## File Sizes After Obfuscation" >> $GITHUB_STEP_SUMMARY
          
          for file in minified/*; do
            size=$(stat -c%s "$file")
            echo "- [$(basename "$file")](https://ratpi-studio.github.io/ratpi-badge/minified/$(basename "$file")) : ${size} bytes" >> $GITHUB_STEP_SUMMARY
          done
